name: Sanity Checks

on:
  workflow_run:
    workflows: Build
    types: completed

jobs:
  sanity-debian:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Performs sanity test on MetricsHub archive on Debian
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          run-id: ${{ github.event.workflow_run.id }}
          pattern: metricshub-linux-package-*
          path: build-output
      - uses: ChristopheClermont/metricshub-sanity-action@main
